main:
# Enable (true) or disable (false) support ColoredTags plugin
  coloredtags: false
lang:
### Language settings ###
  help_title: "Commands Help"
  help_help: "This help page"
  help_clear: "Clear current prefix"
  help_me: "Set prefix for you"
  help_set: "Set prefix for player"
  help_reset: "Reset player prefix"
  help_reload: "Reload RiPrefix config"
  perm: "You don't have permission to use this command."
  corrupted: "§cERROR: Player not found!"
  changed: "§aYour prefix has been successfully changed!"
  deleted: "§dYour prefix has been removed!"
  opchange: "§dPlayer's prefix has been changed!"
  reset: "§aPlayer's prefix has been reset!"