main:
# Select permissions plugin:
# 0 - PermissionsEx
# 1 - GroupManager
  mode: 0
# Enable (true) or disable (false) support ColoredTags plugin
  coloredtags: false
lang:
### Language settings ###
  help_title: "Commands Help"
  help_help: "This help page"
  help_me: "Set prefix for you"
  help_set: "Set prefix for player"
  help_reset: "Reset player prefix"
  perm: "You don't have permission to use this command."
  corrupted: "The mode of the plugin is not correct. Check the configuration."
  changed: "§aYour prefix has been successfully changed!"
  deleted: "§dYour prefix has been removed!"
  opchange: "§dPlayer's prefix has been changed!"
  reset: "§aPlayer's prefix has been reset!"