name: RiPrefix
main: me.ridys.RiPrefix.RiPrefix
load: POSTWORLD
author: Ridys
description: The plugin allows your players to set prefixes in the chat
website: https://ci.dmitry.win/job/RiPrefix/
version: ${version}
commands:
   rips:
      description: Plugin help
      usage: Use /rips for help with this command