# WARN: When you update the plugin, all comments will be deleted
main:
# Plugin will add this prefix to any prefix in game chat
  left-chat-text: "&6["
# Plugin will add this suffix to any prefix in game chat
  right-chat-text: "&6]"
# Plugin will add this prefix to any prefix in TAB (ColoredTags)
  left-tab-text: "&c["
# Plugin will add this suffix to any prefix in TAB (ColoredTags)
  right-tab-text: "&c] "
# Enable (true) or disable (false) support ColoredTags plugin
  coloredtags: false
misc:
# Minimum prefix length (with special symbols)
  min-prefix-length: 3
# Maximum prefix length (with special symbols)
  max-prefix-length: 16
# Specify words that are not allowed in the prefix
  ignore-prefixes:
    - Admin
    - Moderator
lang:
### Language settings ###
  help_title: "Commands Help"
  help_help: "This help page"
  help_clear: "Clear current prefix"
  help_me: "Set prefix for you"
  help_set: "Set prefix for player"
  help_reset: "Reset player prefix"
  help_reload: "Reload RiPrefix config"
  perm: "You don't have permission to use this command."
  corrupted: "§cERROR: Player not found!"
  changed: "§aYour prefix has been successfully changed!"
  deleted: "§dYour prefix has been removed!"
  opchange: "§dPlayer's prefix has been changed!"
  reset: "§aPlayer's prefix has been reset!"
  forbidden: "§cThe prefix contains forbidden words."
  length_check_failed: "§cThe prefix can contain at least 3 characters and not more than 16 characters."
  player_only: "§cOnly players can use this"
# don't change this
version: 3