# WARN: When you update the plugin, all comments will be deleted
main:
# Plugin will add this prefix to any prefix in game chat
  left-chat-text: "&6["
# Plugin will add this suffix to any prefix in game chat
  right-chat-text: "&6]"
# Plugin will add this prefix to any prefix in TAB (ColoredTags)
  left-tab-text: "&c["
# Plugin will add this suffix to any prefix in TAB (ColoredTags)
  right-tab-text: "&c] "
# Enable (true) or disable (false) support ColoredTags plugin
  coloredtags: false
lang:
### Language settings ###
  help_title: "Commands Help"
  help_help: "This help page"
  help_clear: "Clear current prefix"
  help_me: "Set prefix for you"
  help_set: "Set prefix for player"
  help_reset: "Reset player prefix"
  help_reload: "Reload RiPrefix config"
  perm: "You don't have permission to use this command."
  corrupted: "§cERROR: Player not found!"
  changed: "§aYour prefix has been successfully changed!"
  deleted: "§dYour prefix has been removed!"
  opchange: "§dPlayer's prefix has been changed!"
  reset: "§aPlayer's prefix has been reset!"
# don't change this
version: 1